import {ScrollView, StyleShee, Text} from 'react-native'
import React from 'react'

const ComoEstudar = () => {
return(<ScrollView>
    <Text key={1} style={{fontSize:20,marginBottom:10 ,alignSelf:'center', marginRight:10, marginTop:10, color:'#000'}}>Como devo estudar o conteudo?</Text>
    <Text key={2} style={{fontSize:16,marginBottom:10,marginLeft:10,textAlign:'justify' ,marginRight:10, marginTop:10, color:'#000'}}>{'O método a ser utilizado para estudos é algo extremamente subjetivo. Alguns estudantes preferem a ajuda dos professores e colegas para aprofundar-se em determinados assuntos, mas há quem prefira o estudo individual. Fato é que não existe forma certa ou errada, o importante é estudar sempre e com disciplina. Para definir uma técnica de aprendizado, o aluno deve, em primeiro lugar, levar em consideração o seu comportamento e o grau de dificuldade de assimilação quando está em grupo e quando está sozinho. Concentração, motivação e rendimento devem ser avaliados e comparados nas duas situações.\n\nDicas para estudar sozinho\n\nÉ de grande valia que o aluno revise o conteúdo teórico por meio de anotações em cadernos ou dos textos em livros e apostilas, mas é necessário também a realização de exercícios de fixação para amadurecer o processo de aprendizado. Priorize as atividades das disciplinas consideradas mais difíceis. Em conteúdos mais teóricos, o fichamento dos principais textos é a melhor saída. Preferindo a escrita à mão em vez de digitar, a tendência é uma assimilação mais eficaz. O importante aqui não é copiar fragmentos de um livro, mas, sim, elencar palavras e termos essenciais para ajudar na memorização de determinados assuntos. Quando possível, use canetas coloridas e marca-textos para destacar informações relevantes.\n\nCronograma\n\nAlém de conhecer a melhor forma de estudar, o aluno precisa saber qual é o período do dia em que rende melhor e organizar o programa de estudos de forma a privilegiar esses horários. No entanto, é preciso ter cuidado, pois essa programação também pode atrapalhar o rendimento. Um roteiro de estudos fechado pode ser cansativo e desmotivador, então, elaborar um itinerário de estudos flexível e com intervalos regulares é essencial para não desanimar. Vale lembrar que os estudantes precisam respeitar o próprio corpo. Usar as pausas para se exercitar e realizar um lanche saudável é uma forma de manter a saúde física alinhada com o rendimento intelectual.\n\nSe sentir necessário, copie o conteúdo e não esqueça de realizar o simulado'}</Text>
</ScrollView>)
}

export default ComoEstudar;